app/usercenter/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, SelectField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from flask_babel import _, lazy_gettext as _l
from app.models import User

class form_edit_profile(FlaskForm):
    username = StringField(_l('Username'))
    email = StringField(_l('Email'))
    name = StringField(_l('Name'))
    submit = SubmitField(_l('Submit'))

class form_edit_role(FlaskForm):
    rolename = StringField(_l('Role'))
    old_rolename = StringField(_l('Old_Role'))
    submit = SubmitField(_l('Submit'))

class form_edit_role_add_perm(FlaskForm):
    permissiontoadd = SelectField(_l('Permission'), coerce=int)

class form_add_role(FlaskForm):
    roletoadd = StringField(_l('Role'))

class form_edit_permission(FlaskForm):
    permissionname = StringField(_l('Permission Name'))
    permissionaction = StringField(_l('Permission Action'))
    submit = SubmitField(_l('Submit'))

class form_edit_role_for_user(FlaskForm):
    role = SelectField(_l('Role'), coerce=int)
    submit = SubmitField(_l('Submit'))

app/usercenter/__init__.py
from flask import Blueprint

bp = Blueprint('usercenter', __name__)

from app.usercenter import routes

app/usercenter/routes.py
from flask import render_template, redirect, url_for, flash, request
from werkzeug.urls import url_parse
from flask_login import login_user, logout_user, current_user
from flask_babel import _
from app import db
from flask_login import current_user, login_required
from app.usercenter import bp
from app.usercenter.forms import form_edit_profile, form_edit_role, form_edit_permission, form_edit_role_add_perm, form_edit_role_for_user, form_add_role
from app.models import User, Role, Roletopermission, Permission, Usertorole

@bp.route('/lobby', methods=['GET', 'POST'])
def lobby():
    userlist = db.session.query(User).all()
    rolelist = db.session.query(Role).all()
    permissionlist = db.session.query(Permission).all()
    Usertorolelist = db.session.query(Usertorole).all()
    Roletopermissionlist = db.session.query(Roletopermission).all()
    return render_template('usercenter/lobby.html',
                           title=_('User Management'),
                           userlist=userlist,
                           rolelist=rolelist,
                           permissionlist=permissionlist,
                           usertorolelist=Usertorolelist,
                           roletopermissionlist=Roletopermissionlist
                           )

@bp.route('/show_user/<user>', methods=['GET', 'POST'])
@bp.route('/show_user', defaults={'user':'ALL'}, methods=['GET', 'POST'])
def list_user(user):
    if user=='ALL':
        userlist = db.session.query(User).all()
    else:
        userlist = db.session.query(User).filter(User.username==user).all()
    if len(userlist) == 0:
        return redirect(url_for('usercenter.list_user', user='ALL'))

    #Usertorolelist = db.session.query(Usertorole).join(Role, Usertorole.role_id== Role.id).filter(Usertorolelist.userid==current_user.id).all()
    #Roletopermissionlist = db.session.query(Roletopermission).join(Usertorolelist, Usertorolelist.role_id==Roletopermission.role_id).all()
    return render_template('usercenter/show_user.html',
                           title=_('User Management'),
                           datalist = userlist)



@bp.route('/add_role', methods=['GET', 'POST'])
def add_role():
    form=form_add_role()
    if current_user.check_permission('usercenter_role_add'):
        if form.validate_on_submit():
            if db.session.query(Role).filter(Role.rolename==form.roletoadd.data).count() == 0:
                newrole = Role(rolename=form.roletoadd.data)
                db.session.add(newrole)
                db.session.commit()
                flash ('Role has been added!')
            else:
                flash ('Role already exists!')
        else:
            print(form.errors)
            return render_template('usercenter/add_role.html', form=form)
    else:
        flash ('You have no permission to add new roles')
    return redirect(url_for('usercenter.list_role'))

@bp.route('/show_role', methods=['GET', 'POST'])
def list_role():
    form=form_add_role()
    page = request.args.get('page', 1, type=int)
    rolelist = db.session.query(Role).outerjoin(Roletopermission, Roletopermission.role_id == Role.id).all()

    for entry in rolelist:
        print (entry.rolename)

    return render_template('usercenter/show_role.html',
                           title=_('Role Management'),
                           form=form,
                           datalist = rolelist)

@bp.route('/show_permission', methods=['GET', 'POST'])
def list_permission():
    permissionlist = db.session.query(Permission).join(Roletopermission, Roletopermission.role_id == Permission.id).all()
    return render_template('usercenter/show_permission.html', title=_('Permission Management'), datalist = permissionlist)

@bp.route('/edit_profile_remove_role/<username>/<role>', methods=['GET', 'POST'])
@login_required
def usermanagement_revoke_role(username, role):
    if current_user.is_authenticated:
        if current_user.check_permission('usercenter_user_edit') and username != None:
            if User.query.filter(User.username == username).count() == 1:
                usertoedit = username
                user = User.query.filter(User.username == usertoedit).first()
                db.session.query(Usertorole).filter(Usertorole.user_id==user.id).filter(Usertorole.role_id==role).delete()
                db.session.commit()
            else:
                flash("No legal user found")
                usertoedit = current_user.username
        else:
            usertoedit = current_user.username
            flash ('You are not allowed to change other user settings')
            return redirect(url_for('usercenter.usermanagement', username=user.username))
    return redirect(url_for('usercenter.usermanagement', username=user.username))

@bp.route('/edit_profile_remove_permission/<role>/<permission>', methods=['GET', 'POST'])
@login_required
def usermanagement_revoke_permission(role, permission):
    role = role.replace("%20"," ")
    if current_user.is_authenticated:
        if current_user.check_permission('usercenter_role_edit') and permission != None:
            if Role.query.filter(Role.rolename == role).count() == 1:
                roletoedit = Role.query.filter(Role.rolename == role).first()
                db.session.query(Roletopermission).filter(Roletopermission.role_id==roletoedit.id).filter(Roletopermission.permission_id==permission).delete()
                db.session.commit()
            else:
                flash("No legal Role found")
                return redirect(url_for('usercenter.rolemanagement', role=role))
        else:
            flash ('You are not allowed to change Role settings')
            return redirect(url_for('usercenter.rolemanagement', role=role))
    return redirect(url_for('usercenter.rolemanagement', role=role))

@bp.route('/edit_profile', defaults={'username': None}, methods=['GET', 'POST'])
@bp.route('/edit_profile/<username>', methods=['GET', 'POST'])
@login_required
def usermanagement(username):
    if current_user.is_authenticated:
        if current_user.check_permission('usercenter_user_edit') and username != None:
            if User.query.filter(User.username == username).count() == 1:
                usertoedit = username
            else:
                flash("No legal user found")
                usertoedit = current_user.username
        else:
            usertoedit = current_user.username
            flash ('You are not allowed to change other user settings')
            return redirect('usercenter.usermanagement', username=username)
        user = User.query.filter(User.username == usertoedit).first()
        roles = Role.query.all()
        form = form_edit_profile()
        form2 = form_edit_role_for_user()
        form2.role.choices=gamelist = [(g.id, g.rolename) for g in Role.query.all()]
        if form2.validate_on_submit():
            if db.session.query(Usertorole).filter(Usertorole.user_id == current_user.id).filter(Usertorole.role_id==form2.role.data).count() == 0:
                newrole = Usertorole(role_id = form2.role.data, user_id = user.id)
                db.session.add(newrole)
                db.session.commit()
        if form.validate_on_submit():
            if User.query.filter(User.username == form.username.data).count() == 0 and form.username.data!=user:
                if form.username.data == "":
                    flash("NO emptry username allowed")
                else:
                    user.username=form.username.data
                    flash('Username has been updated')

            user.email=form.email.data
            user.real_name=form.name.data
            db.session.commit()
            flash('User has been updated')
        return render_template('usercenter/edit_profile.html',
                               title=_('Edit User'),
                               form=form,
                               form2=form2,
                               user=user)


@bp.route('/edit_role', defaults={'role': None}, methods=['GET', 'POST'])
@bp.route('/edit_role/<role>', methods=['GET', 'POST'])
@login_required
def rolemanagement(role):
    if current_user.is_authenticated:
        if current_user.check_permission('usercenter_role_edit'):
            if role != None:
                role = role.replace("%20","+")
                print(role)
                if Role.query.filter(Role.rolename == role).count() == 1:
                    roletoedit = role
                else:
                    flash("No legal role found")
                    return redirect(url_for('usercenter.list_role'))
            else:
                return redirect(url_for('usercenter.lobby'))
        else:
            flash ('You are not allowed to change')
            return redirect(url_for('usercenter.lobby'))

        role = Role.query.filter(Role.rolename == roletoedit).first()
        form = form_edit_role()
        if form.validate_on_submit():
            if form.old_rolename.data != form.rolename.data:
                if Role.query.filter(Role.rolename == form.old_rolename.data).count() == 1:
                    role.rolename=form.rolename.data
                    db.session.commit()
                    flash('Rolename has been changed to '+form.rolename.data)
                    print(role.rolename)
                    return redirect(url_for('usercenter.rolemanagement', role=role.rolename))

                if Role.query.filter(Role.rolename == form.old_rolename.data).count() == 0:
                    newrole = Role(rolename=form.rolename.data)
                    db.session.add(newrole)
                    db.session.commit()
                    flash('Rolename '+form.rolename.data+' has been created ')
                    print(role.rolename)
                else:
                    flash('Rolename already exists')
        flash (roletoedit)
        permissionlist =db.session.query(Permission).all()

        form2=form_edit_role_add_perm()

app/templates/usercenter/add_permission.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">UserCenter</h1>
          <span class="color-text-a">Add Permission</span>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">{{ title }}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
              Add
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>


<div class="container">
  <div class="row">
    <div class="col-md-7">
      <div class="card-box-c foo">
        <div class="card-header-c d-flex">
          <div class="card-box-ico">
            <div class="card-title-c align-self-center row">
              <span class="fa fa-edit"></span>
            </div>
            <h2 class="title-c">{{_('NEW Permission')}}</h2>
          </div>
        </div>
        <div class="card-body-c">
          <p class="content-c">
            <form role="form" class="form-inline" method="post">
                {{ form.csrf_token() }}
              <div class="row inline">
                {{form.permissionname.label}}{{form.permissionname(class_="form-control", placeholder="Name")}}
              </div>
              <div class="row inline">
                {{form.permissionaction.label}}{{form.permissionaction(class_="form-control", placeholder="action")}}
                <button type="submit" class="btn btn-success"> Add </button>
              </div>
          </form>
          </p>
        </div>
        <div class="card-footer-c">
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

app/templates/usercenter/add_role.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">UserCenter</h1>
          <span class="color-text-a">Add Role</span>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">{{ title }}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
              Profile
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>


<div class="container">
  <div class="row">
    <div class="col-md-4">
      <form role="form" class="form-inline" method="post">
          {{ form.csrf_token() }}
        <div class="row inline">
          {{form.roletoadd(class_="form-control")}}
          </div>
          <div class="row inline">
          <button type="submit" class="btn btn-success"> Add </button>
        </div>
    </form>
    </div>
  </div>
</div>

{% endblock %}

app/templates/usercenter/edit_profile.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">UserCenter</h1>
          <span class="color-text-a">Edit Profile</span>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">{{ title }}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
              Profile
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>

<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card-box-c foo">
        <div class="card-header-c d-flex">
          <div class="card-box-ico">
            <h2 class="title-c align-self-center">{{user.username}}<span class="fa fa-edit"></span></h2>
            <img src="{{ url_for('static', filename=user.image_name)}}" alt="" class="img-d img-fluid" style="min-width: 100px; max-width: 300px; height: 200px;"><br>
            <a href="{{ url_for('main.upload_image', target='user', user=user.username)}}">Upload Image</a>
          </div>
        </div>
        <div class="card-body-c">

          <form role="form" class="content-c form-inline" method="post">
            {{ form.csrf_token() }}
            <div class="row inline">
              <table>
                <tr>
                  <td>{{form.username.label}} </td><td> {{form.username(class_="form-control", size=12, value=user.username)}}</td>
                </tr><tr>
                  <td>{{form.email.label}} </td><td> {{form.email(class_="form-control", size=12,value=user.email)}}</td>
                </tr><tr>
                  <td>{{form.name.label}}</td><td>  {{form.name(class_="form-control", size=12,value=user.real_name)}}</td>
                </tr><tr><td></td><td><button type="submit" class="btn btn-success"> Modify </button></td></tr>
              </table>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="row">
        <div class="container">
          <div>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Role</th>
                </tr>
              </thead>
              <tbody>
                {% for item in user.role %}
                <tr>
                  <td scope="row">
                    <a href="{{url_for('usercenter.rolemanagement', role=item.rolename)}}" class="link-two"> {{item.rolename}}</a>
                  </td>
                  <td>
                    <a href="{{url_for('usercenter.usermanagement_revoke_role', username=user.username, role=item.id)}}" class="link-two"><span class="fa fa-remove"></span></a>
                  </td>
                </tr>
                {% endfor %}
                <tr>
                  <td  scope="row"></td>
                  </tr>
                  <tr>
                    <td scope="row">
                      <form role="form" class="form-inline" method="post">
                          {{ form2.csrf_token() }}
                        <div class="row">
                          {{_("Add Role")}}
                          </div>
                        <div class="row inline">
                          {{form2.role(class_="form-control")}}
                          </div>
                          <div class="row inline">

                          <button type="submit" class="btn btn-success"> Add </button>
                        </div>
                    </form>
                    </td>
                    </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

{% endblock %}

app/templates/usercenter/edit_role.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">UserCenter</h1>
          <span class="color-text-a">Edit Role</span>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">{{ title }}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
              Profile
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>


<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card-box-c foo">
        <div class="card-header-c d-flex">
          <div class="card-box-ico">
            <div class="card-title-c align-self-center row">
              <span class="fa fa-edit"></span>
            </div>
            {% if role.rolename.lower().find("admin") >= 0 %}
              <img src="{{ url_for('static', filename='img/role.png')}}" alt="" class="img-d img-fluid">
            {% else %}
              {% if role.rolename.lower().find("test") >= 0 %}
                <img src="{{ url_for('static', filename='img/explode_user.png')}}" alt="" class="img-d img-fluid">
              {% else  %}
                {% if role.rolename.lower().find("guest") >= 0 %}
                <img src="{{ url_for('static', filename='img/scarlet.png')}}" alt="" class="img-d img-fluid">
                {% else  %}
                <img src="{{ url_for('static', filename='img/mrrobot.png')}}" alt="" class="img-d img-fluid">
                {% endif  %}
              {% endif  %}
            {% endif  %}
            <h2 class="title-c">{{role.rolename}}</h2>
          </div>
        </div>
        <div class="card-body-c">
          <p class="content-c">
            <form role="form" class="form-inline" method="post">
                {{ form.csrf_token() }}
              <div class="row inline">
                {{form.rolename.label}}{{form.rolename(class_="form-control", value=role.rolename)}}
                {{form.old_rolename(class_="form-control", value=role.rolename, hidden=true)}}
                <button type="submit" class="btn btn-success"> Modify </button>
              </div>
          </form>
          </p>
        </div>
        <div class="card-footer-c">
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="row">
        <div class="container">
          <div>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Role</th>
                </tr>
              </thead>
              <tbody>
                {% for item in role.permission %}
                <tr>
                  <td scope="row">
                    <a href="{{url_for('usercenter.permissionmanagement', permission=item.permissionname)}}" class="link-two"> {{item.permissionname}}</a>
                  </td>
                  <td>
                    <a href="{{url_for('usercenter.usermanagement_revoke_permission',permission=item.id, role=role.rolename)}}" class="link-two"><span class="fa fa-remove"></span></a>
                  </td>
                </tr>
                {% endfor %}
                <tr>
                  <td  scope="row"></td>
                  </tr>
                <tr>
                  <td scope="row">
                    <form role="form" class="form-inline" method="post">
                        {{ form2.csrf_token() }}
                      <div class="row">
                        {{_("Add Permission")}}
                        </div>
                      <div class="row inline">
                        {{form2.permissiontoadd(class_="form-control")}}
                        </div>
                        <div class="row inline">

                        <button type="submit" class="btn btn-success"> Add </button>
                      </div>
                  </form>
                  </td>
                  </tr>
              </tbody>
            </table>
            <hr>
            <!-- <form role="form" class="form-inline" method="post">
            <div class="row inline">
              { { form.csrf_token() } }
            { { form2.permissiontoadd(class_="form-control", size=1, choices=[0,'127.0.0.1'], value='127.0.0.1') } }
              <button type="submit" class="btn btn-success"> Add </button>
            </div>
            </form> -->
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

{% endblock %}

app/templates/usercenter/show_permission.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">UserCenter</h1>
          <span class="color-text-a">Manage Permission</span>
        </div>
      </div>
      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">{{ title }}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
              Collection
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>
  <!--/ Agents Grid Star /-->
  <section class="agents-grid grid">
    <div class="container">
      <div class="row">
          <div class="col-sm-12">
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">Permission</th>
              <th>
                <div class="row">
              <a href="{{ url_for('usercenter.add_role') }}" class="link-two">  <span class="fa fa-plus"></span> Permission</a>
              </div>
              </th>
            </tr>
          </thead>
          <tbody>
            {% for entry in datalist %}
            <tr>
              <td scope="row">
                <a href="{{ url_for('usercenter.permissionmanagement', permission=entry.permissionname) }}" class="link-two">{{entry.permissionname}}
                  <br> </a>
              </td>
              <td></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    </div>
  </section>
  <!--/ Agents Grid End /-->

{% endblock %}

app/templates/usercenter/show_role.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<section class="intro-single">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-8">
        <div class="title-single-box">
          <h1 class="title-single">UserCenter</h1>
          <span class="color-text-a">Manage Role</span>
        </div>
        <div class="row">
        <a href="{{ url_for('usercenter.add_role') }}" class="link-two"><span class="fa fa-plus"></span>  role</a>
        </div>
      </div>

      <div class="col-md-12 col-lg-4">
        <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="#">{{ title }}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
              Collection
            </li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
</section>
  <!--/ Agents Grid Star /-->
  <section class="agents-grid grid">
    <div class="container">
      <div class="row">
        {% for entry in datalist %}
        <div class="col-md-4">
          <div class="card-box-d">
            <div class="card-img-d">
              {% if entry.rolename.lower().find("admin") >= 0 %}
                <img src="{{ url_for('static', filename='img/role.png')}}" alt="" class="img-d img-fluid">
              {% else %}
                {% if entry.rolename.lower().find("test") >= 0 %}
                  <img src="{{ url_for('static', filename='img/explode_user.png')}}" alt="" class="img-d img-fluid">
                {% else  %}
                  {% if entry.rolename.lower().find("guest") >= 0 %}
                  <img src="{{ url_for('static', filename='img/scarlet.png')}}" alt="" class="img-d img-fluid">
                  {% else  %}
                  <img src="{{ url_for('static', filename='img/mrrobot.png')}}" alt="" class="img-d img-fluid">
                  {% endif  %}
                {% endif  %}
              {% endif  %}
            </div>
            <div class="card-overlay card-overlay-hover">
              <div class="card-header-d">
                <div class="card-title-d align-self-center">
                  <h3 class="title-d">
                    <a href="{{ url_for('usercenter.rolemanagement', role=entry.rolename) }}" class="link-two">{{entry.role_id}}

                      <br>{{entry.rolename}}</a>
                  </h3>
                </div>
              </div>
              <div class="card-body-d">
                <p class="content-d color-text-a">
                  {% for item in entry.permission %}<br>
                    {{item.permissionname}}
                    {{item.id}}
                  {% endfor %}
                </p>
                <div class="info-agents color-a">
                  <p>
                    <strong>Phone: </strong> +54 356 945234</p>
                  <p>
                    <strong>Email: </strong> agents@example.com</p>
                </div>
              </div>
              <div class="card-footer-d">
                <div class="socials-footer d-flex justify-content-center">
                  <ul class="list-inline">
                    <li class="list-inline-item">
                      <a href="{{ url_for('usercenter.rolemanagement', role=entry.rolename) }}" class="link-one">
                        <i class="fa fa-pen" aria-hidden="true"></i>
                      </a>
                    </li>
                    <!-- <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="fa fa-twitter" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="fa fa-pinterest-p" aria-hidden="true"></i>
                      </a>
                    </li> -->
                    <!-- <li class="list-inline-item">
                      <a href="#" class="link-one">
                        <i class="fa fa-dribbble" aria-hidden="true"></i>
                      </a>
                    </li> -->
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

    </div>
  </section>
  <!--/ Agents Grid End /-->

{% endblock %}